### ISSUE TITLE
App stops as soon as i create profile

### ISSUE THREAD

**Issue by davidSchlosser** [gateship-one/malp#12] opened 2017-01-02 03:25 UTC
I just installed MALP. Immediately after creating my initial profile using my servers IP address the app stops. It doesn't restart, even after reboot. Clear the app data and problem repeats. My device is Nexus 7, running android 6.0.1.

**Comment by djselbeck** [comment] 2017-01-02 09:03
Thanks for reporting the issue. Unfortunately I am not sure what is causing the problem. 

Is it possible to extract an logcat from the crash? Or can you send me the exact profile data you tried (per mail)

**Comment by davidSchlosser** [comment] 2017-01-02 09:43
I don't know how to use logcat.

Name: New Profile
Hostname: 192.168.1.254
Password: (blank)
port:6600

**Comment by djselbeck** [comment] 2017-02-05 12:13
I'm not able to reproduce this and have no information to investigate. Closing it

**Closed by djselbeck** 2017-02-05 12:13 UTC
Labels: help wanted, need information
