### ISSUE TITLE
RemotePlaybackSession not terminated on LineageOS

### ISSUE THREAD

**Issue by sbruder** [gateship-one/malp#38] opened 2017-03-04 11:43 UTC
Since I open M.A.L.P, it adds to the android system a lot of new volume controls with the »cast« symbol, so it’s almost impossible to control the volume afterwards. Is there a procedure missing to remove the controls? The controls are still there after force stopping M.A.L.P.
I’m using Android 7.1.1
![uhisokjyqxoa7dtvbtnuha](https://cloud.githubusercontent.com/assets/15986681/23578463/61d3085a-00cf-11e7-8a64-3927acd8f821.jpg)

**Comment by djselbeck** [comment] 2017-03-04 11:48
I'll have to investigate this. I'm not able to reproduce this so this makes debugging a bit difficult.

Which device are you using?

**Comment by sbruder** [comment] 2017-03-04 12:20
I’m using a Samsung Galaxy Note n7000. I’m using NightOwl LineageOS 14.1, but no Xposed or things like that. It may be a ROM bug, but as it according to my tests only appears with M.A.L.P, it not seems to be a ROM bug.

**Comment by djselbeck** [comment] 2017-03-04 12:21
I can only confirm, that it is not happening with lineage 14.1 without modifications on a BQ m5. The remote playback sessions are terminated correctly on this device.

**Comment by djselbeck** [comment] 2017-03-04 12:32
Correction: I can reproduce this on lineage 14.1. I'll investigate this later

**Comment by djselbeck** [comment] 2017-03-04 12:52
e526c45658d9d1063db26c3f63f1d6602a4023e1 should fix it.

**Comment by djselbeck** [comment] 2017-03-06 17:14
I've created a minimal application [here](https://github.com/djselbeck/android_remoteplaybacktest) . If one alternates fast between the start and stop button multiple remote playback sessions will remain. 

This only happens on lineageos so this is no MALP bug unless someone points me to the error in the minimal code [here](https://github.com/djselbeck/android_remoteplaybacktest/blob/master/app/src/main/java/com/example/hendrik/remoteplaybacktest/MainActivity.java) .

**Comment by djselbeck** [comment] 2017-03-08 17:47
It is fixed in a build for my BQ Aquaris M5 that I've just build (repo sync 1 1/2 hours away)

**Closed by djselbeck** 2017-03-08 17:47 UTC
Labels: help wanted, wontfix
