### ISSUE TITLE
getting multiple volume sliders

### ISSUE THREAD

**Issue by eprst** [gateship-one/malp#102] opened 2018-02-12 17:28 UTC
hi
getting this when changing silence profile using hardware switch on my oneplus 3t
v. 1.1.13
![screenshot_20180206-022411](https://user-images.githubusercontent.com/661098/36110182-9a0d559c-0fd6-11e8-9c25-8a06d97fa9c6.jpg)

**Comment by djselbeck** [comment] 2018-02-12 19:16
Probably a duplicate of #37

**Comment by djselbeck** [comment] 2018-02-13 19:23
What Android version are you using? Which rom? Stock rom? Lineage? If you don't provide any more information there is nothing to do. Although I don't think it is a problem of MALP anyway

**Comment by eprst** [comment] 2018-02-13 19:37
OnePlus 3T stock Oreo rom, OxygenOS 5.0.1
All the sliders go away when I kill the app.

**Comment by djselbeck** [comment] 2018-02-13 19:52
You can download this [apk](https://nextcloud.djselbeck.de/index.php/s/IaakyLxgpbUiBNW) and alternating click on start stop and then change the volume. Do you see one or multiple volume bars?

If you feel uncomfortable installing arbitary apks you can compile it yourself from:

https://github.com/djselbeck/android_remoteplaybacktest

**Comment by eprst** [comment] 2018-02-13 20:19
hm. I can't reproduce it with this example, however something isn't right.

* Toggling h/w slider -> can see the normal "ring" volume", volume buttons work as expected
* Start remote session. toggle switch shows remote volume, volume buttons change it
* Start remote session again. Volume buttons still change remote volume, but toggle switch now again only shows the normal ring volume, no "cast" icon there.

Actually, managed to reproduce:
very quickly tap start and stop buttons (start/stop/start/stop etc), then toggle h/w switch - get lots of remote volume sliders like in the screenshot. They go away after a few seconds though. At some point I somehow managed to make one of them stay forever (till I killed the app), but I can't find the exact steps.

ROM bug?

**Comment by djselbeck** [comment] 2018-02-13 20:20
Probably, LineageOS hat something like this as well.

**Comment by djselbeck** [comment] 2018-05-27 09:47
Closing this due to inactivity and probably out of scope of MALP

**Closed by djselbeck** 2018-05-27 09:47 UTC
