### ISSUE TITLE
Multiple entries of the same album

### ISSUE THREAD

**Issue by Nohoy** [gateship-one/malp#71] opened 2017-10-02 18:36 UTC
After switching from MPDroid to M.A.L.P., I noticed albums that where properly named and tagged would suddenly show up multiple under the same artist, using the same album name, and containing the same songs. Renaming and homogenizing the tags wouldn't help, even when using Mp3tag, Foobar2000, and MusicBrainz. Switching between both apps confirmed the problem to only exist in M.A.L.P.

Is this an error on my side, and if so, how can it be fixed?

**Comment by vaughanl** [comment] 2017-10-06 11:08
Same problem here.

**Comment by djselbeck** [comment] 2017-10-06 11:23
Perhaps they have a different AlbumArtist Tag, then they are shown multiple times. This is intended (e.g. Greatest Hits by Bob and Greatest Hits by Alice)

**Comment by Nohoy** [comment] 2017-10-06 11:26
Unfortunately, this is not the case, as this was the first thing I checked. Wouldn't that problem be fixed if we were to switch from AlbumArtist tag to Artist in the settings?

**Comment by djselbeck** [comment] 2017-10-06 11:28
No the setting has no effect on the album view. Only on the artist list

**Comment by Nohoy** [comment] 2017-10-06 11:40
Ah, too bad. The problem, however, still remains after having renamed all tags in the files multiple times. Some reduction in duplicates was seen when removing/homogenizing the release dates, but it would at most be reduced to 2. Is there a limit on the number of files M.A.L.P. can handle?

**Comment by vaughanl** [comment] 2017-10-06 11:58
This happens for several albums in my library. The only one whose tags I examined is such that I can find no explanation for the behaviour other than a bug in M.A.L.P. The Album, Artist, Album Artist and Date tags match exactly for every track. It's an annoyance that I'd like to see fixed but as the only competitor I'd use doesn't handle multiple server profiles I'm unlikely to stop using M.A.L.P.

**Comment by djselbeck** [comment] 2017-10-06 13:35
The album list is grouped by AlbumArtist and Album date and musicbrainz_id. If any of those is not equal for all albums they are listed multiple times.

**Comment by djselbeck** [comment] 2017-10-06 13:35
https://github.com/gateship-one/malp/blob/master/app/src/main/java/org/gateshipone/malp/mpdservice/mpdprotocol/MPDCommands.java#L31 is where the command is created

**Comment by transiti0nary** [comment] 2017-10-13 21:10
I also experienced this issue and deduced it must be due to a discrepancy in musicbrainz_id tags. 

All albums this problem appeared on were my own made 'mutt rips' from when beets hasn't correctly tagged some special edition albums in a way I like and I have corrected the bonus tracks so they (in theory) would display more nicely.

I think the problem is the first part of the album which was correctly tagged by beets must have a musicbrainz_id, whereas the bonus tracks I have added in later without beets tagging them either has no musicbrainz_id or has one which differs from the other tracks.

This is consistent with how the separate appearances of albums in MALP are always one of the original, beets-tagged tracks and one listing of the tracks I manually added to my library later.

As a quick fix is there any way to prevent MPD from reading musicbrainz tags?

**Comment by svendickman** [comment] 2017-10-18 07:31
I experience similar problems and have determined that the issue is with the song dates.  MALP creates a different album for each year of each song.  This is not very good for Greatest Hits compilations albums that have been recorded at different years.  
  Other MDP clients do not behave this way, and I don't think MALP used to behave this way.  
Is there any way to disable this sorting or do I have to retag all of my songs?

**Comment by djselbeck** [comment] 2017-10-18 07:38
This because MALP needs to group by date to sort artist albums by date. Like I said it groups by 3 criteria at the moment. If any of them is different it is listed as a separate album which makes sense. Even for the date tag. Imagine an artist releasing multiple "Greatest Hits" albums. 

Another example are Soundtracks (e.g. Caprica exists two times in my library as different albums, one is the pilot soundtrack and one for the rest of the series, if it were not for MBID they could be separated by date)

**Comment by svendickman** [comment] 2017-10-18 07:46
Hi, thanks for replying so quickly.  And thanks for developping a great application.
For an artist with multiple Greatest Hits or Soundtracks albums I would find renaming the 2nd album more logical than using the song dates.

**Comment by djselbeck** [comment] 2017-10-18 07:52
> Hi, thanks for replying so quickly. And thanks for developping a great application.
You're very welcome.

If you are tagging your files manually  you can do it. If you tag them corresponding to a central database like MusicBrianz you can't.

I'll check later if perhaps some kind of intelligent heuristic can work around this but I'm not sure. Music libraries usually are so diverse that it is nearly impossible to find a way to suit all requirements.

**Comment by Nohoy** [comment] 2017-10-18 07:54
@djselbeck , I found an album that displays the behaviour, but the tracks are to large to be sent by mail. 

Essential is to note here that, while the album is listed as one in the album-section, it shows up twofold in the artist-section. This issue is still apparent when setting all dates to be the same (so, it's exactly as transiti0nary describes).

**Comment by djselbeck** [comment] 2017-10-18 07:54
It can be year, albumartist or title ;) if all are uniform you should only see it once

**Comment by bae22** [comment] 2018-01-01 20:24
Thanks @djselbeck  for the great new release of MALP the other day. Like others above, I discovered that I have albums appearing multiple times in my list - for me it was because of different dates in my tags.

I know that everyone has a different way of tagging their music, and you can't cater for everyone, but is there any possibility of adding an option to choose whether the "date" is used as a criteria for identifying albums? Personally I like to record the date of the performance if possible (which is important with classical music where performers record a work multiple times) rather than the date of release of the CD.

Just thought it was worth at least asking!

**Comment by djselbeck** [comment] 2018-02-08 20:04
One bug about this was addressed with cf6cf860d00d4dbbbf27c155ffc27d408b921063 .

Might fix some of this issue

**Comment by djselbeck** [comment] 2018-02-14 21:14
Can anyone confirm if this issue is still present in MALP 1.1.14?

**Comment by Nohoy** [comment] 2018-02-19 14:27
I've checked it, and all seems fixed.

**Comment by djselbeck** [comment] 2018-02-19 14:28
Thanks for the reply ;) and sorry for my stubbornness.

I'll close the issue for now. If it is  still valid please reopen

**Closed by djselbeck** 2018-02-19 14:28 UTC
Labels: need information
