### ISSUE TITLE
Library albums are unusable

### ISSUE THREAD

**Issue by axelsimon** [gateship-one/malp#45] opened 2017-03-30 00:08 UTC
In recent versions of MALP, the library is now populated with artists, which is nice and looks nice (it remained empty until a few versions ago for be).

However, if I enter any artist, I just see all the albums in the library, instead of the selected artist's albums. This makes the library unusable for me.

I'm on MALP 1.1.4 connected to Mopidy (I see the server properties page suggests using the "real MPD", why is this? Mopidy implements the mpd protocol, I thought this was transparent to clients…).

Hope this helps, thanks.

**Comment by djselbeck** [comment] 2017-03-30 05:43
> In recent versions of MALP, the library is now populated with artists, which is nice and looks nice (it remained empty until a few versions ago for be).

That's because I tried to implement workarounds for Mopidy (which I tested with Mopidy 2.1). It worked but not completely correct.

> I'm on MALP 1.1.4 connected to Mopidy (I see the server properties page suggests using the "real MPD", why is this? Mopidy implements the mpd protocol, I thought this was transparent to clients…).

The problem with Mopidy is that they say they implement the MPD protocol but they do so in a very sloppy and bad manner. For example, they say that they implement MPD protocol version 0.19 (and that's all a mpd client sees) but don't implement critical features of this version.

This results in client failure hence the note to the user that they should use the real MPD. I even contacted the developers over IRC and over their bugtracker but they don't seem to care that much.

This is why I say that Mopdiy might or might not work and don't provide any support for it. IMHO mopidy is a bad reimplementation of a perfectly good software (MPD) which performs not even faster but also works much more reliable (Mopidy took over an hour to scan my music library whereas MPD took a few minutes. Mopidy takes a few seconds to reply to requests whereas MPD almost ever replies instantly).

As bad as it is for you I will now close the issue because it is not a MALP issue (MALP is a mpd client and not a mopidy client) because the problem is Mopidy.

References:
https://github.com/mopidy/mopidy/issues/1315
https://github.com/mopidy/mopidy/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20mpd%20

**Closed by djselbeck** 2017-03-30 05:43 UTC
